
replicas: 2 

deployment:
  name: flask-app-deployment
container:
  name: flask-app-container
  image:
    repository: dockerelvis/python-memcached
    image_tag: "latest" 
  port: 8095
readinessProbe:
  port: 8095
  initialDelaySeconds: 10
  periodSeconds: 15
livenessProbe:
  port: 8095
  initialDelaySeconds: 20
  periodSeconds: 300
volumeMounts:
  name: flask-app-volume
volume:
  claim: 
    name: nfs-pvc
terminationGracePeriodSeconds: 20
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  name: flask-app-service
  port:
    exposePort: 8096
    targetPort: 8095

resource:
  config:
    name: flask-resouce
  data:
    memory_request: "128Mi"
    memory_limit: "256Mi"
    cpu_request: "250m"
    cpu_limit: "500m"

env:
  config:
    name: flask-env
  data:
    host: "memcached-service"
    port: "11211"
    os: "kubernetes"

ingress:
    dns:
      host: my-flask-app.com
    port:
      number: 8096