apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.resource.config.name }}
  labels:
    app: flask-app
data:
  memory-request: "{{ .Values.resource.data.memory_request }}"
  memory-limit: "{{ .Values.resource.data.memory_limit }}"
  cpu-request: "{{ .Values.resource.data.cpu_request }}"
  cpu-limit: "{{ .Values.resource.data.cpu_limit }}"
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env.config.name }}
  labels:
    app: flask-app
data:
  MEMCACHED_HOST: "{{ .Values.env.data.host }}"
  MEMCACHED_PORT: "{{ .Values.env.data.port }}"
  OPERATING_SYSTEM: "{{ .Values.env.data.os }}"